name: Build macOS App

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install py2app

      - name: Build macOS app bundle
        run: |
          python setup.py py2app

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v3
        with:
          name: PDFScanner-macOS
          path: dist/*.app
